<?php

namespace ContainerXz8lLIZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GZbJ0PUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GZbJ0PU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GZbJ0PU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'apprenant' => ['privates', '.errored..service_locator.GZbJ0PU.App\\Entity\\Apprenant', NULL, 'Cannot autowire service ".service_locator.GZbJ0PU": it references class "App\\Entity\\Apprenant" but no such service exists.'],
        ], [
            'apprenant' => 'App\\Entity\\Apprenant',
        ]);
    }
}
