<?php

namespace ContainerLHLuGoX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XKo_E_BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xKo.E.B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xKo.E.B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'apprenantRepository' => ['privates', 'App\\Repository\\ApprenantRepository', 'getApprenantRepositoryService', true],
        ], [
            'apprenantRepository' => 'App\\Repository\\ApprenantRepository',
        ]);
    }
}
