<?php

namespace ContainerLHLuGoX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TKHdKt3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tKHdKt3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tKHdKt3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evaluationRepository' => ['privates', 'App\\Repository\\EvaluationRepository', 'getEvaluationRepositoryService', true],
        ], [
            'evaluationRepository' => 'App\\Repository\\EvaluationRepository',
        ]);
    }
}
