<?php

namespace ContainerLHLuGoX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApprenantService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.GZbJ0PU.App\Entity\Apprenant' shared service.
     *
     * @return \App\Entity\Apprenant
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.GZbJ0PU": it references class "App\\Entity\\Apprenant" but no such service exists.');
    }
}
