<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLHLuGoX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLHLuGoX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLHLuGoX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLHLuGoX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLHLuGoX\App_KernelDevDebugContainer([
    'container.build_hash' => 'LHLuGoX',
    'container.build_id' => 'b87e2f18',
    'container.build_time' => 1625329075,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLHLuGoX');
